debug: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example.seaturtlesoup: debug
    org.springframework.servlet : debug #req, res log
    org.hibernate.type.descriptor.sql.BasicBinder : trace #jpa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seaturtlesoup
    username: crumbled
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${api_key}
  model:
    name: gpt-4o